### ISSUE TITLE
[TODO] Service 계층과 Repository 계층의 역할 구분

### ISSUE THREAD

**Issue by choewy** [choewy/typescript-magazine#1]
현재 프로젝트는 MVC 디자인 패턴을 적용하고 있습니다. 단, 전통적인 MVC(Model-View-Controller) 패턴이 아닌 Nest.js 또는 Java Spring에서의 Service 계층과 Repository 계층을 적용하고자 합니다. 지금까지 작성한 코드를 보면, Service 계층과 Repository 계층의 역할 경계가 애매한 것으로 보입니다. 따라서, 각각의 계층을 다음과 같은 역할을 부여하여 명확하게 구분하고자 합니다.

- Controller : 라우터 역할, 미들웨어 또는 Service 계층을 통해 특정 URL에 대한 절차 수행
- Model : 특정 데이터베이스 모델 명시
- Service
    - 현재 : 비즈니스 로직의 일부만 수행(예 : 회원가입 시 계정 존재여부 확인 후 분기처리를 Repository에서 담당하고 있음
    - 개선 : 특정 기능에 대한 모든 비즈니스 로직 수행(예 : 회원가입 시 DB 처리를 제외한 모든 비즈니스 로직을 수행)
    - [x] : Signup
        - [x] : Repository.findByEmail
        - [x] : 이메일 존재 여부 확인 및 분기 처리
        - [x] : 비밀번호 암호화 처리
        - [x] : Repository.createUser
        - [x] : 토큰 발급 및 응답
    - [x] : Signin
        - [x] : Repository.findByEmail
        - [x] : 이메일 존재 여부 확인 및 1차 분기 처리
        - [x] : 비밀번호 일치 여부 확인 및 2차 분기 처리
        - [x] : 토큰 발급 및 응답
    - [x] : Auth
        - [x] : Repository.findByPayload
        - [x] : 이메일 존재 여부 확인 및 1차 분기 처리
        - [x] : 사용자 정보 필터 및 응답
- Repository
    - 현재 : DB 처리 뿐만 아니라 비즈니스 로직의 일부도 함께 수행
    - 개선 : 특정 모델에 대한 데이터베이스 처리만을 담당
        - [x] : ~findByPayload~
        - [x] : findByEmail
        - [x] : findPassword
        - [x] : createUser
